/* automatically generated by rust-bindgen */

pub type size_t = ::std::os::raw::c_uint;
pub type ssize_t = ::std::os::raw::c_int;
pub type intptr_t = ::std::os::raw::c_int;
pub type off_t = ::std::os::raw::c_longlong;
pub type pid_t = ::std::os::raw::c_int;
pub type uid_t = ::std::os::raw::c_uint;
pub type gid_t = ::std::os::raw::c_uint;
pub type useconds_t = ::std::os::raw::c_uint;
extern "C" {
    pub static mut optarg: *mut ::std::os::raw::c_char;
    pub static mut optind: ::std::os::raw::c_int;
    pub static mut opterr: ::std::os::raw::c_int;
    pub static mut optopt: ::std::os::raw::c_int;
}
extern "C" {
    pub fn pipe(arg1: *mut ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn pipe2(arg1: *mut ::std::os::raw::c_int,
                 arg2: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn close(arg1: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn posix_close(arg1: ::std::os::raw::c_int,
                       arg2: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn dup(arg1: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn dup2(arg1: ::std::os::raw::c_int, arg2: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn dup3(arg1: ::std::os::raw::c_int, arg2: ::std::os::raw::c_int,
                arg3: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn lseek(arg1: ::std::os::raw::c_int, arg2: off_t,
                 arg3: ::std::os::raw::c_int) -> off_t;
    pub fn fsync(arg1: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn fdatasync(arg1: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn read(arg1: ::std::os::raw::c_int,
                arg2: *mut ::std::os::raw::c_void, arg3: size_t) -> ssize_t;
    pub fn write(arg1: ::std::os::raw::c_int,
                 arg2: *const ::std::os::raw::c_void, arg3: size_t)
     -> ssize_t;
    pub fn pread(arg1: ::std::os::raw::c_int,
                 arg2: *mut ::std::os::raw::c_void, arg3: size_t, arg4: off_t)
     -> ssize_t;
    pub fn pwrite(arg1: ::std::os::raw::c_int,
                  arg2: *const ::std::os::raw::c_void, arg3: size_t,
                  arg4: off_t) -> ssize_t;
    pub fn chown(arg1: *const ::std::os::raw::c_char, arg2: uid_t,
                 arg3: gid_t) -> ::std::os::raw::c_int;
    pub fn fchown(arg1: ::std::os::raw::c_int, arg2: uid_t, arg3: gid_t)
     -> ::std::os::raw::c_int;
    pub fn lchown(arg1: *const ::std::os::raw::c_char, arg2: uid_t,
                  arg3: gid_t) -> ::std::os::raw::c_int;
    pub fn fchownat(arg1: ::std::os::raw::c_int,
                    arg2: *const ::std::os::raw::c_char, arg3: uid_t,
                    arg4: gid_t, arg5: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn link(arg1: *const ::std::os::raw::c_char,
                arg2: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
    pub fn linkat(arg1: ::std::os::raw::c_int,
                  arg2: *const ::std::os::raw::c_char,
                  arg3: ::std::os::raw::c_int,
                  arg4: *const ::std::os::raw::c_char,
                  arg5: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn symlink(arg1: *const ::std::os::raw::c_char,
                   arg2: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn symlinkat(arg1: *const ::std::os::raw::c_char,
                     arg2: ::std::os::raw::c_int,
                     arg3: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn readlink(arg1: *const ::std::os::raw::c_char,
                    arg2: *mut ::std::os::raw::c_char, arg3: size_t)
     -> ssize_t;
    pub fn readlinkat(arg1: ::std::os::raw::c_int,
                      arg2: *const ::std::os::raw::c_char,
                      arg3: *mut ::std::os::raw::c_char, arg4: size_t)
     -> ssize_t;
    pub fn unlink(arg1: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn unlinkat(arg1: ::std::os::raw::c_int,
                    arg2: *const ::std::os::raw::c_char,
                    arg3: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn rmdir(arg1: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn truncate(arg1: *const ::std::os::raw::c_char, arg2: off_t)
     -> ::std::os::raw::c_int;
    pub fn ftruncate(arg1: ::std::os::raw::c_int, arg2: off_t)
     -> ::std::os::raw::c_int;
    pub fn access(arg1: *const ::std::os::raw::c_char,
                  arg2: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn faccessat(arg1: ::std::os::raw::c_int,
                     arg2: *const ::std::os::raw::c_char,
                     arg3: ::std::os::raw::c_int, arg4: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn chdir(arg1: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn fchdir(arg1: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn getcwd(arg1: *mut ::std::os::raw::c_char, arg2: size_t)
     -> *mut ::std::os::raw::c_char;
    pub fn alarm(arg1: ::std::os::raw::c_uint) -> ::std::os::raw::c_uint;
    pub fn sleep(arg1: ::std::os::raw::c_uint) -> ::std::os::raw::c_uint;
    pub fn pause() -> ::std::os::raw::c_int;
    pub fn fork() -> pid_t;
    pub fn execve(arg1: *const ::std::os::raw::c_char,
                  arg2: *const *mut ::std::os::raw::c_char,
                  arg3: *const *mut ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn execv(arg1: *const ::std::os::raw::c_char,
                 arg2: *const *mut ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn execle(arg1: *const ::std::os::raw::c_char,
                  arg2: *const ::std::os::raw::c_char, ...)
     -> ::std::os::raw::c_int;
    pub fn execl(arg1: *const ::std::os::raw::c_char,
                 arg2: *const ::std::os::raw::c_char, ...)
     -> ::std::os::raw::c_int;
    pub fn execvp(arg1: *const ::std::os::raw::c_char,
                  arg2: *const *mut ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn execlp(arg1: *const ::std::os::raw::c_char,
                  arg2: *const ::std::os::raw::c_char, ...)
     -> ::std::os::raw::c_int;
    pub fn fexecve(arg1: ::std::os::raw::c_int,
                   arg2: *const *mut ::std::os::raw::c_char,
                   arg3: *const *mut ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn _exit(arg1: ::std::os::raw::c_int);
    pub fn getpid() -> pid_t;
    pub fn getppid() -> pid_t;
    pub fn getpgrp() -> pid_t;
    pub fn getpgid(arg1: pid_t) -> pid_t;
    pub fn setpgid(arg1: pid_t, arg2: pid_t) -> ::std::os::raw::c_int;
    pub fn setsid() -> pid_t;
    pub fn getsid(arg1: pid_t) -> pid_t;
    pub fn ttyname(arg1: ::std::os::raw::c_int)
     -> *mut ::std::os::raw::c_char;
    pub fn ttyname_r(arg1: ::std::os::raw::c_int,
                     arg2: *mut ::std::os::raw::c_char, arg3: size_t)
     -> ::std::os::raw::c_int;
    pub fn isatty(arg1: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn tcgetpgrp(arg1: ::std::os::raw::c_int) -> pid_t;
    pub fn tcsetpgrp(arg1: ::std::os::raw::c_int, arg2: pid_t)
     -> ::std::os::raw::c_int;
    pub fn getuid() -> uid_t;
    pub fn geteuid() -> uid_t;
    pub fn getgid() -> gid_t;
    pub fn getegid() -> gid_t;
    pub fn getgroups(arg1: ::std::os::raw::c_int, arg2: *mut gid_t)
     -> ::std::os::raw::c_int;
    pub fn setuid(arg1: uid_t) -> ::std::os::raw::c_int;
    pub fn setreuid(arg1: uid_t, arg2: uid_t) -> ::std::os::raw::c_int;
    pub fn seteuid(arg1: uid_t) -> ::std::os::raw::c_int;
    pub fn setgid(arg1: gid_t) -> ::std::os::raw::c_int;
    pub fn setregid(arg1: gid_t, arg2: gid_t) -> ::std::os::raw::c_int;
    pub fn setegid(arg1: gid_t) -> ::std::os::raw::c_int;
    pub fn getlogin() -> *mut ::std::os::raw::c_char;
    pub fn getlogin_r(arg1: *mut ::std::os::raw::c_char, arg2: size_t)
     -> ::std::os::raw::c_int;
    pub fn gethostname(arg1: *mut ::std::os::raw::c_char, arg2: size_t)
     -> ::std::os::raw::c_int;
    pub fn ctermid(arg1: *mut ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn getopt(arg1: ::std::os::raw::c_int,
                  arg2: *const *mut ::std::os::raw::c_char,
                  arg3: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn pathconf(arg1: *const ::std::os::raw::c_char,
                    arg2: ::std::os::raw::c_int) -> ::std::os::raw::c_long;
    pub fn fpathconf(arg1: ::std::os::raw::c_int, arg2: ::std::os::raw::c_int)
     -> ::std::os::raw::c_long;
    pub fn sysconf(arg1: ::std::os::raw::c_int) -> ::std::os::raw::c_long;
    pub fn confstr(arg1: ::std::os::raw::c_int,
                   arg2: *mut ::std::os::raw::c_char, arg3: size_t) -> size_t;
    pub fn lockf(arg1: ::std::os::raw::c_int, arg2: ::std::os::raw::c_int,
                 arg3: off_t) -> ::std::os::raw::c_int;
    pub fn gethostid() -> ::std::os::raw::c_long;
    pub fn nice(arg1: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn sync();
    pub fn setpgrp() -> pid_t;
    pub fn crypt(arg1: *const ::std::os::raw::c_char,
                 arg2: *const ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn encrypt(arg1: *mut ::std::os::raw::c_char,
                   arg2: ::std::os::raw::c_int);
    pub fn swab(arg1: *const ::std::os::raw::c_void,
                arg2: *mut ::std::os::raw::c_void, arg3: ssize_t);
    pub fn usleep(arg1: ::std::os::raw::c_uint) -> ::std::os::raw::c_int;
    pub fn ualarm(arg1: ::std::os::raw::c_uint, arg2: ::std::os::raw::c_uint)
     -> ::std::os::raw::c_uint;
    pub fn brk(arg1: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int;
    pub fn sbrk(arg1: intptr_t) -> *mut ::std::os::raw::c_void;
    pub fn vfork() -> pid_t;
    pub fn vhangup() -> ::std::os::raw::c_int;
    pub fn chroot(arg1: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn getpagesize() -> ::std::os::raw::c_int;
    pub fn getdtablesize() -> ::std::os::raw::c_int;
    pub fn sethostname(arg1: *const ::std::os::raw::c_char, arg2: size_t)
     -> ::std::os::raw::c_int;
    pub fn getdomainname(arg1: *mut ::std::os::raw::c_char, arg2: size_t)
     -> ::std::os::raw::c_int;
    pub fn setdomainname(arg1: *const ::std::os::raw::c_char, arg2: size_t)
     -> ::std::os::raw::c_int;
    pub fn setgroups(arg1: size_t, arg2: *const gid_t)
     -> ::std::os::raw::c_int;
    pub fn getpass(arg1: *const ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn daemon(arg1: ::std::os::raw::c_int, arg2: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn setusershell();
    pub fn endusershell();
    pub fn getusershell() -> *mut ::std::os::raw::c_char;
    pub fn acct(arg1: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
    pub fn syscall(arg1: ::std::os::raw::c_long, ...)
     -> ::std::os::raw::c_long;
    pub fn execvpe(arg1: *const ::std::os::raw::c_char,
                   arg2: *const *mut ::std::os::raw::c_char,
                   arg3: *const *mut ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn issetugid() -> ::std::os::raw::c_int;
}
